### ISSUE TITLE
关于React的学习

### ISSUE THREAD

**Issue by MonFig** [liuzhenangel/react-ruby-china#4]
比较想通过这个项目学习一下React项目的基本实现思路，请问您有时间写一下这个项目的教程文档之类的东西吗？或者您有时间简单介绍一下您的项目的构建思路吗？感谢感谢🙏！

**Comment by liuzhenangel** [comment]
@MonFig 我之前写过一篇详解文章， 你可以参考一下： http://liuzhen.me/articles/33
